<a href="https://colab.research.google.com/github/ShlokGhadekar/PythonBasics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) is a powerful Python library for numerical computing, widely used for handling arrays, performing mathematical operations, and working with scientific data.

In [1]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5]) #1d array
print("1D array",arr1)
arr2=np.array([[1,2,3],[4,5,6]]) #2d array
print("2D array",arr2)
arr3=np.array([[[1,2],[3,4]],[[5,6,],[7,8]]]) #3d array(tensor)
print("3D array",arr3)

print("Array shape: ",arr2.shape)
print("Array size: ",arr2.size)
print("data type: ",arr2.dtype)
print("No of dimensions: ",arr2.ndim)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]]
3D array [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Array shape:  (2, 3)
Array size:  6
data type:  int64
No of dimensions:  2


In [6]:
np.zeros((3, 3))          # 3x3 matrix of zeros
np.ones((2, 2))           # 2x2 matrix of ones
np.eye(3)                 # 3x3 identity matrix
np.random.rand(3, 3)      # Random numbers between 0 and 1
np.random.randint(1, 10, (2, 2))  # Random integers

array([[9, 2],
       [4, 4]])

In [7]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print(arr[0, 1])   # Access single element (20)
print(arr[:, 1])   # Get entire 2nd column
print(arr[1, :])   # Get entire 2nd row
print(arr[0:2, 1:3])  # Slicing

20
[20 50]
[40 50 60]
[[20 30]
 [50 60]]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(np.dot(a, b))  # Dot product: 1*4 + 2*5 + 3*6 = 32
print(np.mean(a))  # Mean
print(np.sum(a))   # Sum
print(np.max(a))   # Max

[5 7 9]
[ 4 10 18]
32
2.0
6
3


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape((2, 3))
print(arr_reshaped)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(np.vstack((a, b)))  # Vertical stack
print(np.hstack((a, b.T)))  # Horizontal stack

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [11]:
np.linspace(1, 10, 5)  # Create 5 equally spaced numbers from 1 to 10
np.argmax(arr)         # Index of the max value
np.argmin(arr)         # Index of the min value
np.sort(arr)           # Sort array
np.unique(arr)         # Get unique values

array([1, 2, 3, 4, 5, 6])

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])  # B has shape (2,)

print(A + B)

arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])

X=np.array([[10,20,30],[40,50,60],[70,80,90]])
rows=np.array([0,2])
cols=np.array([1,2])

print(X[rows,cols])

[[11 22]
 [13 24]]
[4 5 6]
[20 90]


In [20]:
arr = np.array([1, 2, 3, 4, 5])

# Min-Max Normalization (scales data between 0 and 1)
norm_arr = (arr - arr.min()) / (arr.max() - arr.min())

# Z-score Normalization (Mean = 0, Std = 1)
std_arr = (arr - arr.mean()) / arr.std()

In [21]:
#Random data generation
np.random.seed(42)  # Ensures reproducibility
rand_data = np.random.rand(5, 5)  # 5x5 matrix with random values between 0 and 1

In [22]:
mean, std_dev = 0, 1
normal_data = np.random.normal(mean, std_dev, (3, 3))  # 3x3 matrix from Normal distribution